### ISSUE TITLE
Create a meta/mail.yml file

### ISSUE THREAD

**Issue by XioNoX** [napalm-automation/napalm-ansible#11]
``` yaml
- src: https://github.com/napalm-automation/napalm-ansible/
  version: master
  name: napalm
  path: roles
```

In requirements.yml
then:
ansible-galaxy install -r requirements.yml --force

Returns
 [WARNING]: - napalm was NOT installed successfully: ERROR! this role does not appear to have a meta/main.yml file.
