### ISSUE TITLE
Error with napalm_install_config for nxos_ssh OS - Search pattern never detected in send_command_expect: [hostname]

### ISSUE THREAD

**Issue by AdamSmith-Mtl** [napalm-automation/napalm-ansible#142]
I am using napalm-ansible to install configuration on various equipment and I am getting an error on a specific Nexus7k host.

Everything works fine on my other three Nexus (and on other types of equipment and on all equipment in my dev environment), so this should not be a problem with the way I use the module.

Here is the part in my playbook where I use the napalm_install_config module:

```
---

- name: "{{ equipment_family }} - Install the configuration using the napalm-ansible library"
  napalm_install_config:
    hostname: "{{ ansible_ssh_host }}"
    username: "{{ smi_username }}"
    password: "{{ smi_password }}"
    dev_os: "{{ napalm_install_config_dev_os }}"
    config_file: "{{ master_config_file }}"
    commit_changes: "{{ not ansible_check_mode }}"
    replace_config: False
    get_diffs: True
    diff_file: "{{ diff_file }}"
    timeout: "{{ napalm_install_config_timeout }}"
  any_errors_fatal: true
```

And here is the verbose output I get when this part runs on the problematic host:

```
The full traceback is:
  File "/tmp/ansible_gJc7b8/ansible_module_napalm_install_config.py", line 311, in main
    device.commit_config()
  File "/usr/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 54, in commit_config
    self._save_to_checkpoint(self.backup_file)
  File "/usr/lib/python2.7/site-packages/napalm/nxos_ssh/nxos_ssh.py", line 645, in _save_to_checkpoint
    self.device.send_command(command)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1112, in send_command
    search_pattern))

fatal: [QCDRVLS202]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "archive_file": null, 
            "candidate_file": null, 
            "commit_changes": true, 
            "config": null, 
            "config_file": "/var/lib/awx/projects/_79__customer_provisioning_v72/playbooks/../files/configs/2018-08-24_11:35:30/QCDRVLS202/___master.conf", 
            "dev_os": "nxos_ssh", 
            "diff_file": "/var/lib/awx/projects/_79__customer_provisioning_v72/playbooks/../files/diffs/2018-08-24_11:35:30/QCDRVLS202.diff", 
            "get_diffs": true, 
            "hostname": "10.199.254.47", 
            "optional_args": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "hostname": "10.199.254.47", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": 60, 
                "username": "removed"
            }, 
            "replace_config": false, 
            "timeout": 60, 
            "username": "removed"
        }
    }, 
    "msg": "cannot install config: Search pattern never detected in send_command_expect: QCDRVLS202\\#"
}

```
As I said, it always happens on the QCDRVLS202 Nexus even though the configuration that I send to this host is the same as the one I send to other hosts.

This error doesn't happen in check_mode. From what I gathered while searching on Google, this might be due to the fact that this specific host might be slower to respond than the three other similar hosts, which makes the prompt "time-out" while waiting for the "QCMTRLS202#" text on the command line, but I can't seem to find a way to make it wait longer.

If you require additional information, I will be glad to provide it as it is very important to me to solve this issue .

Thank you!
