### ISSUE TITLE
filter interfaces_ip does not work on napalm_get_facts

### ISSUE THREAD

**Issue by rainierpineda2** [napalm-automation/napalm-ansible#149]
I have the following Ansible code. The commands takes over two minutes to execute and the the device only has one IP. If I use facts as a filter, there are no issues.

- name: Get basic device facts via NAPALM
  napalm_get_facts:
    hostname: 10.45.230.250
    username: "{{ USERNAME }}"
    password: "{{ PASSWORD }}"
    dev_os: "{% if nb_platform=='cisco-ios' %}ios{%elif nb_platform=='cisco-nxos'%}nxos{%endif%}"
    filter: "interfaces_ip"

I get the following error message:

TASK [validate_device : Get basic device facts via NAPALM] *************************************************
fatal: [netbox]: FAILED! => {"changed": false, "msg": "[interfaces_ip] cannot retrieve device data: Search p
attern never detected in send_command_expect: show\\ run\\ interface\\ F"}

**Comment by ktbyers** [comment]
@rainierpineda2 Try increasing the global_delay_factor:

```
- name: Get basic device facts via NAPALM
  napalm_get_facts:
  hostname: 10.45.230.250
  username: "{{ USERNAME }}"
  password: "{{ PASSWORD }}"
  dev_os: "{% if nb_platform=='cisco-ios' %}ios{%elif nb_platform=='cisco-nxos'%}nxos{%endif%}"
  filter: "interfaces_ip"
  optional_args: {"global_delay_factor": 2}        # try 2 and if that still fails, then try 4
```
