### ISSUE TITLE
Incorrect module-path

### ISSUE THREAD

**Issue by jurajbgh** [napalm-automation/napalm-ansible#151]
#Ansible Version:
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/maxson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
--------------------
#Ansible.cfg 
[defaults]
library = /usr/local/lib/python2.7/dist-packages/napalm_ansible/modules
action_plugins = /usr/local/lib/python2.7/dist-packages/napalm_ansible/plugins/action
---
#Playbook
```
---
- name: Validate
  hosts: all
  tasks:
    - name: Compare
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: cisco
        password: cisco
        dev_os: "ios"
        config_file: "CFGS/check.txt"
        commit_changes: False
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
```
--------------------------------------

#issue
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/maxson/playbooks/complaiance/merge.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Compare
      ^ here
