### ISSUE TITLE
napalm_install_config not generating diffs

### ISSUE THREAD

**Issue by lvrfrc87** [napalm-automation/napalm-ansible#167]
I generate a config diff with `eos_config` module and I can see the below:
```
    - name: diff the running-config against a master config.
      eos_config:
        diff_against: intended
        intended_config: "{{ lookup('file', './configurations/{{ inventory_hostname }}/renders/{{ config_file_name }}.cfg') }}"
```
```
TASK [diff the running-config against a master config.] **************************************************************
--- before
+++ after
@@ -58,8 +58,8 @@
 spanning-tree mst configuration
    name leaf1-2
    revision 3
-   instance 1 vlan  10-60
-   instance 2 vlan  4000-4002,4010
+   instance 1 vlans 10-60
+   instance 2 vlans 4000-4002,4010
 tacacs-server key 7 071B2949455A00
 tacacs-server host 10.74.34.31 vrf mgmt
 tacacs-server host 10.74.0.31 vrf mgmt
```

When I run the diff with napalm, using the same config_file against the same running config, diff are not generated.

```
    - name: NAPALM diff between running-conf and render.
      napalm_install_config:
        config_file: './configurations/{{ inventory_hostname }}/renders/{{ config_file_name }}.cfg'
        commit_changes: False
        replace_config: False
        get_diffs: True
        diff_file: './configurations/{{ inventory_hostname }}/diffs/{{ config_file_name }}.diff'
        provider: "{{ eos_auth }}"
        timeout: 300
      register: diff_result
    - debug: var=diff_result
```
```
TASK [debug] *********************************************************************************************************
ok: [l1a.r5b1.ams7.nee.tmcs] => {
    "diff_result": {
        "changed": false,
        "failed": false,
        "msg": ""
    }
}
```

I would expect to see the diffs generated by NAPALM as per `eos_config`
