### ISSUE TITLE
napalm module :  Error: "'ascii' codec can't encode characters in position 5396-5398: ordinal not in range(128)"}

### ISSUE THREAD

**Issue by pranayp1687** [napalm-automation/napalm-ansible#202]
Hi ,

We are getting below error when we used napalm_cli module, it's working most of same model firewall device but for some getting below error.
Can you please help.

TASK [rancid : running config command] *****************************************
fatal: [XN-SINCC3-BO105 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode character u'\\\\x93' in position 1364: ordinal not in range(128)"}
...ignoring
fatal: [XN-SINCC3-BO101 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode characters in position 1249-1251: ordinal not in range(128)"}
...ignoring
fatal: [XN-SINTP1-BO101 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode characters in position 8270-8272: ordinal not in range(128)"}
...ignoring
fatal: [XN-SINGS1-BO301 -> localhost]: FAILED! => {"changed": false, "msg": "xmlSAX2Characters: huge text node, line 116061, column 92 (line 116061)"}
...ignoring
fatal: [XN-SINPL1-BO101 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode character u'\\\\xa0' in position 9914: ordinal not in range(128)"}
...ignoring
fatal: [XN-PAOEQ1-BO101 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode characters in position 5396-5398: ordinal not in range(128)"}
...ignoring
fatal: [XN-LAXOW1-BO101 -> localhost]: FAILED! => {"changed": false, "msg": "'ascii' codec can't encode characters in position 9431-9433: ordinal not in range(128)"}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 24: ordinal not in range(128)
fatal: [XNL-HKGCW1-BO104 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1693454675.85-62343020719071/AnsiballZ_napalm_cli.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1693454675.85-62343020719071/AnsiballZ_napalm_cli.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1693454675.85-62343020719071/AnsiballZ_napalm_cli.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.napalm_cli', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 176, in run_module\\n    fname, loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 82, in _run_module_code\\n    mod_name, mod_fname, mod_loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 72, in _run_code\\n    exec code in run_globals\\n  File \\"/tmp/ansible_napalm_cli_payload_egSM2v/ansible_napalm_cli_payload.zip/ansible/modules/napalm_cli.py\\", line 191, in <module>\\n  File \\"/tmp/ansible_napalm_cli_payload_egSM2v/ansible_napalm_cli_payload.zip/ansible/modules/napalm_cli.py\\", line 175, in main\\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 24: ordinal not in range(128)\\n", "module_stdout": "", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring

Below is Playbook task, below variable value we are kept in another file, so ignore that part:

```yaml
- name: running config command
  napalm_cli:
    hostname: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    dev_os: "{{ ansible_network_os }}"
    password: "{{ ansible_password }}"
    args:
      commands: "{{ commands_list }}"
  register: configuration
  # retries: 3
  # delay: 3
  # until: configuration is not failed
  ignore_errors: true
  delegate_to: localhost
```
