### ISSUE TITLE
Research why napalm_get_nxos_ssh.yml was intermittently failing

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#205]
```yaml
---
- name: napalm nxos_ssh
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_interfaces
      napalm.napalm.get_facts:
        filter: facts,interfaces
        dev_os: nxos_ssh

    - ansible.builtin.debug:
        var: napalm_facts
```

TASK [Retrieve get_facts, get_interfaces] ****************************************************************************************
fatal: [nxos1]: FAILED! => {"changed": false, "msg": "[interfaces] cannot retrieve device data: \nPattern not detected: 'nxos1\\\\#' in output.\n\nThings you might try to fix this:\n1. Explicitly set your pattern using the expect_string argument.\n2. Increase the read_timeout to a larger value.\n\nYou can also look at the Netmiko session_log or debug log for more information.\n\n"}
