### ISSUE TITLE
Can napalm-ansible and napalm-panos be used together?

### ISSUE THREAD

**Issue by dmgeurts-mm** [napalm-automation/napalm-ansible#211]
I'm looking for a way to configure panos settings that haven't been exposed by pan-os-python yet (Advanced routing).

napalm-panos works for connecting to a Palo Alto device but from Ansible I can't use network os panos. Can someone tell me if what I'm trying to do is meant to work or not?

`network os panos is not supported`

**Comment by ktbyers** [comment]
Yes, I would think they should work together. Did you verify they are working at the Python + NAPALM level (i.e. completely outside of Ansible)?

@dmgeurts-mm

**Comment by dmgeurts-mm** [comment]
@ktbyers Yes, I can fetch facts from Python using napalm-panos: https://github.com/napalm-automation-community/napalm-panos/issues/123#issuecomment-2592886712

**Comment by ktbyers** [comment]
And you have verified the Python that your ansible is using has both napalm and napalm-panos installed?

**Comment by ktbyers** [comment]
@dmgeurts-mm It looks like Ansible does not have any `ansible_network_os` for `panos`--so try something like this:

```yaml
---
- name: NAPALM get_facts and get_interfaces
  hosts: panos
  connection: local
  gather_facts: False
  vars:
    provider: { "dev_os": "panos" }

  tasks:
    - name: napalm get_facts
      napalm.napalm.get_facts:
        filter: facts,interfaces
        provider: "{{ provider }}"

    - debug:
        var: napalm_facts
```

I would set `ansible_network_os` to a valid value like `ios` or `junos`. I believe the `dev_os` in the provider should overwrite this value.

I could not 100% test this as I don't have a panos device.
