### ISSUE TITLE
Add support for passing of command line arguments (in a manner consistent with Ansible core modules)

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#76]
```
---
- name: NAPALM on IOS 
  hosts: pynet-rtr1
  tasks:
    - name: NAPALM facts
      napalm_get_facts: 
        hostname: "{{ ansible_host }}"
        dev_os: "ios"
```

```
$ ansible-playbook napalm_w_cli.yml -u pyclass -k
SSH password: 

PLAY [NAPALM on IOS] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************
ok: [pynet-rtr1]

TASK [NAPALM facts] **************************************************************************************************************************************************************************************************
fatal: [pynet-rtr1]: FAILED! => {"changed": false, "failed": true, "msg": "username is required"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************
pynet-rtr1                 : ok=1    changed=0    unreachable=0    failed=1   

```

Also should support if using a provider.
