### ISSUE TITLE
Can't install via ansible-galaxy because meta/main.yml is missing

### ISSUE THREAD

**Issue by justdave** [napalm-automation/napalm-ansible#87]
*Steps to reproduce:*

Place the following in requirements.yml:
```yaml
---
- src: https://github.com/napalm-automation/napalm-ansible/
  version: master
  name: napalm
  path: roles
```
then run `ansible-galaxy install -r requirements.yml --force`

*Actual results:*
` [WARNING]: - napalm was NOT installed successfully: this role does not appear to have a meta/main.yml file.`

This file used to exist in napalm: it was added in 4b069028683c53950735d17f4043147c7a71c998

And was removed again in dc34cfc4dc6b7747e88ed96cef94eb01ccb5f61e 6 days ago.
