### ISSUE TITLE
napalm_ping RETURN VALUES

### ISSUE THREAD

**Issue by abelozer** [napalm-automation/napalm-ansible#89]
Documentation says that when echo request fails there should be a response like this:
results:

```
    # when echo request fails
    {"error": "connect: Network is unreachable"}
```

I've tested this and get response like this:

```
"results": {
    "success": {
       "packet_loss": -2,
       "probes_sent": 0,
       "results": [],
       "rtt_avg": 0.0,
       "rtt_max": 0.0,
       "rtt_min": 0.0,
       "rtt_stddev": 0.0
        }
```

My task:

```yaml
  - name: Ping hosts
      napalm_ping:
        destination: "{{ item }}"
        dev_os: ios
        count: "{{ ping_count | default(2) }}"
        provider: "{{ provider }}"
        optional_args: {'port': "{{ port | default(22) }}"}
      with_items: "{{ pinghosts }}"
```
